lang_chi = ['中文',
            '荷兰语',
            '德语',
            '斯洛文尼亚语',
            '匈牙利语',
            '罗马尼亚语',
            '哈萨克语',
            '土耳其语',
            '俄语',
            '意大利语',
            '英语',
            '希腊语',
            '塔吉克语',
            '挪威语',
            '葡萄牙语',
            '芬兰语',
            '丹麦语',
            '法语',
            '瑞典语',
            '阿塞拜疆语',
            '西班牙语',
            '印度尼西亚语',
            '阿拉伯语',
            '尼泊尔语', ]
lang_eng = ['chinese',
            'dutch',
            'german',
            'slovene',
            'hungarian',
            'romanian',
            'kazakh',
            'turkish',
            'russian',
            'italian',
            'english',
            'greek',
            'tajik',
            'norwegian',
            'portuguese',
            'finnish',
            'danish',
            'french',
            'swedish',
            'azerbaijani',
            'spanish',
            'indonesian',
            'arabic',
            'nepali', ]

eng2chi = {eng: chi for eng, chi in zip(lang_eng, lang_chi)}
chi2eng = {chi: eng for eng, chi in zip(lang_eng, lang_chi)}
